services:
  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: DB_prueba
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./prueba/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
